-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "kitchenComment" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "driverRating" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "driverComment" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "postDeliveryTip" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "orderId" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "Review_orderId_key" ON "Review"("orderId");
