ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "payoutMethod" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "upiId" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "accountLast4" TEXT;

ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "payoutMethod" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "upiId" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "accountLast4" TEXT;

ALTER TABLE "Payout" ADD COLUMN IF NOT EXISTS "paymentProofUrl" TEXT;

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "refundRequested" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "refundReason" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "refundRejectedAt" TIMESTAMP(3);
