/**
 * ZOOMO EATS — machine-readable product spec for another AI.
 * Reverse-engineered from https://zoomo-self.vercel.app (customer SPA)
 * on 2026-09-15. Use this file as the source of truth when recreating
 * or extending the product. Every screen, token, flow, and string lives here.
 */
export const ZOOMO_AI_SPEC = {
  product: {
    name: "Zoomo Eats",
    variant: "Customer",
    tagline: "Fastest food delivery with real-time tracking & great offers.",
    liveUrl: "https://zoomo-self.vercel.app",
    backend: "https://zoomo-production.up.railway.app",
    stackObserved: "React + Vite SPA, React Router, Poppins, Tailwind, inline theme objects",
    audience: "End customers ordering food. Merchant users are rejected at login.",
    currency: "INR (₹) even when some catalog prices look USD-like",
    coverage: "45+ cities",
  },

  brand: {
    font: "Satoshi 300/400/500/700/900 (Fontshare)",
    logoMark:
      "Stylized Z: three lime strokes (M6 10H22, M22 10L10 22, M10 22H26) on #0F3D2E rounded square. Header uses an image logo 36px tall.",
    tokens: {
      page: "#F5F7F6",
      surface: "#FFFFFF",
      primary: "#0F3D2E",
      hover: "#145A43",
      accent: "#22C55E",
      textMain: "#0B0F0E",
      textSub: "#6B7280",
      textMuted: "#9CA3AF",
      border: "#E5E7EB",
      borderSoft: "#F0F2F1",
      error: "#DC2626",
      pink: "#EC4899",
      veg: "#16A34A",
      nonveg: "#DC2626",
    },
    gradients: {
      primaryCta: "linear-gradient(135deg, #0F3D2E 0%, #145A43 100%)",
      heroOverlay: "linear-gradient(135deg, rgba(15,61,46,0.82) 0%, rgba(20,90,67,0.72) 100%)",
      menuHero: "linear-gradient(to top, rgba(11,15,14,0.85) 0%, rgba(11,15,14,0.2) 60%, rgba(11,15,14,0.35) 100%)",
    },
    radii: { chip: 999, button: 10, card: 20, sheet: 28, input: 12 },
    shadows: {
      headerScrolled: "0 2px 20px rgba(15,61,46,0.07)",
      cta: "0 2px 8px rgba(15,61,46,0.25)",
      cardHover: "0 12px 40px rgba(15,61,46,0.13)",
      authCard: "0 10px 48px rgba(15,61,46,0.10)",
      search: "0 8px 32px rgba(0,0,0,0.25)",
    },
    motion: "120–180ms ease-out hover; card lifts -3px; image scales 1.05; reduced chrome blur 16px",
  },

  routes: [
    { path: "/", auth: false, screen: "Home / landing with location gate" },
    { path: "/login", auth: false, screen: "Login card" },
    { path: "/signup", auth: false, screen: "Two-step signup" },
    { path: "/restaurants", auth: false, screen: "Full restaurant directory" },
    { path: "/restaurant/:id", auth: false, screen: "Restaurant menu" },
    { path: "/cart", auth: false, screen: "Cart (empty if logged out)" },
    { path: "/checkout", auth: true, screen: "Checkout: delivery / dine-in / takeaway" },
    { path: "/orders", auth: true, screen: "My Orders list" },
    { path: "/orders/:id", auth: true, screen: "Order detail + status" },
  ],

  api: {
    base: "https://zoomo-production.up.railway.app",
    authHeader: "Authorization: Bearer <access_token>",
    tokenKey: "localStorage.access_token",
    endpoints: [
      "GET /users/me",
      "POST /auth/login  → { access_token|accesstoken, user }  user.role MUST be USER (else 'Please login from Merchant app!')",
      "POST /auth/signup",
      "GET /restaurants",
      "GET /restaurants/:id",
      "GET /dishes?restaurantId=",
      "GET /dishes/:id",
      "GET /cart   POST /cart/items {dishId, quantity}  DELETE /cart/items/:id",
      "GET /addresses  POST /addresses",
      "POST /orders  GET /orders/mine  GET /orders/:id",
    ],
  },

  screens: {
    locationModal: {
      title: "Where should we deliver?",
      subtitle: "Enter your address to find nearby restaurants",
      placeholder: "e.g. Koramangala, Bengaluru",
      primary: "Find Food Near Me",
      secondary: "Set later",
      behavior: "First-visit overlay, backdrop blur. Enter submits.",
    },
    header: {
      sticky: true,
      logo: "36px image → home",
      locationChip: "MapPin + current location or 'Set location'",
      loggedOut: ["Login (ghost)", "Sign up (primary gradient)"],
      loggedIn: "User icon + first name (sm+); opens profile sheet",
      cart: "40×40 icon with count badge",
    },
    home: {
      hero: {
        video:
          "https://res.cloudinary.com/dx2qaarhy/video/upload/v1789214802/5899705-uhd_2160_4096_30fps_1.mp4",
        pill: "FAST DELIVERY · 45+ CITIES",
        h1: "What are you craving today?",
        cravingColor: "#22C55E",
        sub: "Set your location to see restaurants near you  OR  Delivering to {location}",
        searchPlaceholder: "Search restaurants, cuisines, dishes...",
        searchBehavior: "Read-only input; click opens full-screen search overlay",
      },
      offerBar: {
        kicker: "LIMITED TIME OFFER",
        copy: "Free delivery on your first 3 orders. No code needed.",
        cta: "Order now",
        ctaBehavior: "Scroll to restaurant grid if logged in, else /login",
      },
      cuisine: {
        heading: "Explore by cuisine",
        chips: [
          "All",
          "Pizza",
          "Burgers",
          "Indian",
          "Chinese",
          "Biryani",
          "Desserts",
          "Beverages",
          "Healthy",
          "Street Food",
        ],
        selected: "primary fill, white text, green shadow",
      },
      grid: {
        headingDefault: "Restaurants near you",
        headingLocated: "Near {location}",
        headingSearch: 'Results for "{q}"',
        count: "{n} available",
        emptyTitle: "Nothing found",
        emptySub: "Try a different search or pick another category",
        card: {
          imageH: 176,
          ratingBadge: "top-right dark pill with star",
          couponBadge: "bottom-left green on primary glass",
          meta: "{eta 25-40 min} · ₹250 for two",
          cta: "Order ›",
          hover: "lift -3px, image scale 1.05, green border",
        },
      },
      why: {
        kicker: "WHY ZOOMO EATS",
        h2: "Faster food. Simpler checkout.",
        cards: [
          { emoji: "⚡", title: "Under 60 seconds", desc: "Orders confirmed and dispatched before you've put your phone down." },
          { emoji: "📍", title: "Real-time tracking", desc: "Watch every step of your delivery on a live map." },
          { emoji: "✅", title: "Quality vetted", desc: "Every restaurant passes our hygiene and rating standards before listing." },
        ],
      },
      footer: {
        bg: "#0F3D2E",
        blurb: "Fastest food delivery with real-time tracking & great offers.",
        explore: ["Restaurants /restaurants", "Offers #", "Support #"],
        legal: ["Terms & Conditions", "Privacy Policy", "Cookie Policy"],
        copyright: "© {year} Zoomo Eats. All rights reserved.",
      },
    },
    login: {
      layout: "Centered card maxWidth 440, radius 28, dark-green header, light page",
      headerTitle: "Welcome back",
      headerSub: "Login to continue your delicious journey",
      fields: ["Email address", "Password"],
      extras: "Forgot password?  (no-op)",
      submit: "Login to Zoomo Eats",
      loading: "3 bouncing lime dots",
      switch: "Don't have an account? Sign up",
      pills: ["Free delivery on signup", "4.8★ rated", "Secure login"],
    },
    signup: {
      steps: 2,
      step1: {
        title: "Create your account",
        sub: "Join thousands ordering smarter every day",
        fields: ["Full name", "Email address"],
        cta: "Continue",
      },
      step2: {
        title: "Almost there!",
        sub: "Set a secure password and you're ready",
        fields: ["Password with 4-segment strength meter"],
        cta: "Create My Account 🎉",
        back: "ghost back to step 1",
      },
      switch: "Already have an account? Login",
      validation: ["Please enter your full name.", "Please enter your email."],
    },
    restaurantMenu: {
      heroH: 240,
      back: "38×38 frosted button",
      title: "restaurant name, rating, 25-40 min, cuisineType, description",
      heading: "Menu",
      empty: "🍽️ No dishes available right now",
      dishRow: {
        vegMark: "14px square, 2px border, 6px inner dot — green veg / red non-veg",
        price: "₹{price} in primary",
        calories: "{n} kcal",
        image: "88×88 radius 14",
        add: "ADD overlay overlapping bottom of image, primary outline; hover fills primary",
        qtyStepper: "shown once quantity > 0",
      },
      viewCartBar: "sticky/fixed bottom when cart has items: qty pill + View Cart + total",
      conflictModal: {
        title: "Start a new cart?",
        body: "Your cart has items from another restaurant. Adding this will clear your current cart.",
        cancel: "Cancel",
        confirm: "Yes, replace",
      },
    },
    cart: {
      emptyTitle: "Your cart is empty",
      emptySub: "Add some delicious food to get started!",
      emptyCta: "Browse restaurants → /restaurants",
      bill: [
        { label: "Subtotal", formula: "sum(price*qty)" },
        { label: "Delivery Fee", formula: "₹29 flat" },
        { label: "Tax & charges (5%)", formula: "subtotal * 0.05" },
      ],
      cta: "Proceed to Checkout · ₹{total}",
    },
    checkout: {
      heading: "Checkout",
      loading: "Loading checkout... / Placing your order... 🍔",
      fulfillment: {
        question: "How would you like this order?",
        options: [
          { id: "DELIVERY", label: "Delivery", sub: "Delivered to your door" },
          { id: "DINE_IN", label: "🍽️ Dine In", sub: "Eat at the restaurant" },
          { id: "TAKEAWAY", label: "Takeaway", sub: "Pick up yourself" },
        ],
      },
      dineIn: {
        when: "When would you like to dine in?",
        guests: "guest / guests",
        pay: "💵 Pay at Restaurant — Pay in cash or card when you arrive",
        online: "💳 Online Payment — Coming soon (disabled)",
        cta: "Book Dine-In · ₹{total}",
      },
      takeaway: {
        when: "When will you pick up?",
        pay: "same as dine-in",
        cta: "Confirm Takeaway · ₹{total}",
      },
      delivery: {
        address: "saved addresses or + Add new address (street, city, state, zipCode)",
        scheduleToggle: "Schedule Delivery",
        tips: [0, 10, 20, 30, 50, "Custom"],
        tipColor: "#EC4899",
        pay: "💰 Cash on Delivery — Pay when your order arrives; Online coming soon",
        ctaScheduled: "Schedule Delivery · ₹{total}",
        ctaNow: "Place Order · ₹{total}",
      },
      promo: {
        title: "Promo Code",
        codes: {
          ZOOMO50: "50% off, capped ₹100",
          BOGO: "₹60 off (labeled Buy 1 Get 1 in chatbot)",
          FREESHIP: "waives ₹29 delivery, min cart ₹199 in chatbot copy",
          HEALTHY20: "20% off, capped ₹80",
          NEWUSER: "₹80 off",
        },
      },
      success: {
        title: "Order Placed! 🎉",
        sub: "You'll receive updates in My Orders",
        motion: "ping ring + confettiFall",
      },
    },
    orders: {
      listTitle: "My Orders",
      row: "restaurant, date, total, status chip, chevron → /orders/:id",
      detail: ["Order #", "Restaurant", "Items Ordered", "payment amount", "status chip"],
      statuses: {
        PENDING: { color: "#D97706", bg: "#FEF3C7" },
        CONFIRMED: { color: "#2563EB", bg: "#DBEAFE" },
        PREPARING: { color: "#EA580C", bg: "#FFEDD5" },
        READYFORPICKUP: { color: "#7C3AED", bg: "#EDE9FE" },
        OUTFORDELIVERY: { color: "#0284C7", bg: "#E0F2FE" },
        DELIVERED: { color: "#16A34A", bg: "#DCFCE7" },
        CANCELLED: { color: "#DC2626", bg: "#FEE2E2" },
      },
    },
    profileSheet: {
      header: "avatar initial, name, email",
      links: [
        { label: "My Orders", path: "/orders" },
        { label: "My Cart", path: "/cart" },
        { label: "All Restaurants", path: "/restaurants" },
      ],
      logout: "Logout (danger, #FFF5F5 / #FEE2E2 hover)",
    },
    chat: {
      name: "Zoomo Assist",
      fab: "fixed bottom 20 right 20, primary circle, title Chat with Zoomo",
      greeting: "Hey! I'm Zoomo 👋 What can I help you with?",
      placeholder: "Ask something...",
      chips: ["Deals 🔥", "Track order", "Payment"],
      replies: {
        deal_or_offer:
          "🔥 Use ZOOMO50 for 50% off, BOGO for Buy 1 Get 1, or FREESHIP for free delivery above ₹199!",
        track_or_order: "Go to My Orders to track your delivery in real-time!",
        deliver: "We deliver to 45+ cities! Set your location on the home screen.",
        pay: "We support UPI, Cards, Wallets, Net Banking & Cash on Delivery!",
        fallback: "Hmm, I didn't get that! Try asking about deals, orders, or restaurants.",
      },
      latencyMs: "1000–1600",
    },
  },

  catalogShape: {
    restaurant: [
      "id",
      "name",
      "description",
      "imageUrl",
      "address",
      "phone",
      "email",
      "openingHours",
      "cuisineType",
      "priceRange",
      "rating",
      "isActive",
      "lat",
      "lng",
      "dishes[]",
    ],
    dish: [
      "id",
      "name",
      "description",
      "price",
      "imageUrl",
      "ingredients",
      "calories",
      "isVegetarian",
      "isVegan",
      "isGlutenFree",
      "isAvailable",
      "preparationTime",
      "restaurantId",
    ],
    observedRestaurants: [
      "Pizza Palace (Italian, 4.5, $$)",
      "Burger Barn (American, 4.3, $$)",
      "Healthy Bites (Healthy, 4.7, $)",
      "RFC fast food (Indian, $)",
      "I Love Pizza (Pizza, veg-forward menu)",
      "Moonlight (Italian, empty menu)",
    ],
  },

  layoutChrome: {
    maxWidth: 1152,
    homePadding: "40px 20px 60px",
    menuMaxWidth: 920,
    authMaxWidth: 440,
    chatWidth: 320,
  },

  recreationNotes: [
    "Match Poppins + forest/lime palette exactly — this is Swiggy-adjacent, not purple SaaS.",
    "Do not add a bottom tab bar; chrome is sticky header + cart FAB/bar + chat FAB.",
    "One restaurant per cart. Conflict modal is mandatory.",
    "Online payment is always disabled ('Coming soon').",
    "Delivery fee ₹29, tax 5%.",
    "Customer app rejects non-USER roles.",
    "Dark mode is forced OFF (html.light, class dark removed).",
  ],
} as const;
